### ISSUE TITLE
❌ [Removal]: Blocklist Cleanup

### ISSUE THREAD

**Issue by AyanokojiK1yotaka** [the-advoid/ad-void#3029]
**URL**:   
**Reason**:
 [i] Target: https://raw.githubusercontent.com/igorskyflyer/ad-void/main/AdVoid.DNS.txt
  [✓] Status: Retrieval successful
  [✓] Parsed 0 exact domains and 2443 ABP-style domains (ignored 98 non-domain entries)
      Sample of non-domain entries:
        - "||doppiocdn"
        - "-pglstatp.com^"
        - ".com/api/users?token=*&uuid=&pii=&in=false^$document"
        - "/?r=dir&zoneid=$document,popup"
        - "://ads.$~image,domain=~ads.8designers.com|~ads.ac.uk|~ads.adstream.com.ro|~ads.allegro.pl|~ads.am|~ads.amazon|~ads.apple.com|~ads.atmosphere.copernicus.eu|~ads.band|~ads.bestprints.biz|~ads.bikepump.com|~ads.brave.com|~ads.buscaempresas.co|~ads.cafebazaar.ir|~ads.colombiaonline.com|~ads.comeon.com|~ads.cvut.cz|~ads.doordash.com|~ads.dosocial.ge|~ads.dosocial.me|~ads.elevateplatform.co.uk|~ads.finance|~ads.google.com|~ads.gree.net|~ads.gurkerl.at|~ads.harvard.edu|~ads.instacart.com|~ads.jiosaavn.com|~ads.kaipoke.biz|~ads.kazakh-zerno.net|~ads.kifli.hu|~ads.knuspr.de|~ads.lapalingo.com|~ads.listonic.com|~ads.magalu.com|~ads.mba|~ads.mercadolivre.com.br|~ads.mgid.com|~ads.microsoft.com|~ads.midwayusa.com|~ads.mobilebet.com|~ads.msstate.edu|~ads.mst.dk|~ads.mt|~ads.nc|~ads.nipr.ac.jp|~ads.olx.pl|~ads.pinterest.com|~ads.quasaraffiliates.com|~ads.red|~ads.rohlik.cz|~ads.route.cc|~ads.safi-gmbh.ch|~ads.scotiabank.com|~ads.selfip.com|~ads.shopee.cn|~ads.shopee.co.th|~ads.shopee.com.br|~ads.shopee.com.mx|~ads.shopee.com.my|~ads.shopee.kr|~ads.shopee.ph|~ads.shopee.pl|~ads.shopee.sg|~ads.shopee.tw|~ads.shopee.vn|~ads.smartnews.com|~ads.snapchat.com|~ads.socialtheater.com|~ads.spotify.com|~ads.studyplus.co.jp|~ads.taboola.com|~ads.tiktok.com|~ads.twitter.com|~ads.typepad.jp|~ads.us.tiktok.com|~ads.viksaffiliates.com|~ads.vk.com|~ads.watson.ch|~badassembly.com|~caravansforsale.co.uk|~fusac.fr|~memo2.nl|~reempresa.org|~satmetrix.com|~seriouswheels.com"

**Comment by igorskyflyer** [comment]
Hello, thanks for your input. I am not quite sure what seems to be the issue here. Could you elaborate?

The provided (sample) rules were intentionally written that way - using wildcards - to cover as much advertisement URLs as possible. Something *wrong* with that?

Looking forward to hear your ideas.

**Comment by AyanokojiK1yotaka** [comment]
i'm using the dns list on my Pihole and it showed that there were many domains being ignored.

That is what i wanted to bring foward.

Is there a way to fix this?

**Comment by igorskyflyer** [comment]
> i'm using the dns list on my Pihole and it showed that there were many domains being ignored.
> 
> That is what i wanted to bring foward.
> 
> Is there a way to fix this?

It's not an actual error per se, it's just that Pi-hole doesn't support the mentioned syntax, I am looking into it, thanks.

**Comment by igorskyflyer** [comment]
After looking into it further online, I found that it's just the way domain parsing is implemented in *Pi-hole*.  

*Unfortunately*, it does **not** support wildcard domains but there is nothing wrong with keeping them in the filter list since other adblockers **do** support them.  

You are free to report any other issues - if any, thank you for opening this issue. ☺️
