### ISSUE TITLE
💔 [Malformed]: Invalid DNS filter syntax rules in DNS filter

### ISSUE THREAD

**Issue by Metrokoto** [the-advoid/ad-void#3062]
Hello, fellow filterlist dev here.

Just letting you know that I noticed that your DNS filter contains rules with invalid syntax, such as rules containing $domain, $xmlhttprequest, as well as URLs such as example.com/ads, and rules that do not start with | or ||.

This may cause issues for some DNS blockers, could you please update the list to follow the AdGuard Home and PiHole syntax correctly?

The following sections have rules that should NOT be present in a DNS filterlist;

! {1} Domains - wildcard (global)
! {2} Domains - RegExp (global)
! {4} Subdomains (global)
! {6} Endpoints (site)

I use AdVoid.DNS with AdGuard Home, and I wish to avoid issues.

Here is a link to a filterlist with valid syntax to follow as a guide;

https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

**Comment by igorskyflyer** [comment]
Hi 👋🏻 @Metrokoto, thank you for raising awareness of this issue.  

I am actually aware of the ongoing issue that is present in the DNS filter list. The issue is caused by the automation system I made and use, which is still in the development stage and lacks some functionality to output proper DNS rules.  

<br>

I use:
- [ADBT](https://github.com/adbt-lang/adbt) (templates)
- [Aria](https://github.com/igorskyflyer/npm-adblock-aria-compiler) (compiler)  

I maintain a single domains list of rules which get compiled into appropriate output filter files. The missing link is that modifiers should be stripped for the DNS list to be **completely** valid, which I plan to add during a week or two, depending on the amount of free time I have.

About other non-domain rules, you are right, I'll evaluate which rules need to be removed from the list completely.

Cheers. 🙋🏻‍♂️

**Comment by igorskyflyer** [comment]
There will be another restructuring of AdVoid's rules soon and any rules that weren't removed by these commits will get removed then. Happy blocking! 🥳
